### ISSUE TITLE
Listagem de blockchains

### ISSUE THREAD

**Issue by fellipeesteves** [apuspayments/WooComercePlugin#1]
Usando o plugin do woocommerce, não consigo selecionar o blockchain de pagamentos. Problema na listagem das blockchains na configuração do plugin.

![3B90C72C-BCDF-4A5A-898A-421EEAC0ACC0](https://user-images.githubusercontent.com/5082030/61982657-d6e80180-afd3-11e9-9319-b9bf06601732.png)

**Comment by fellipeesteves** [comment]
Problema de listagem das blockchains resolvido.

- O erro era decorrente de um filtro implementado de forma equivocada entre os ambientes SANDBOX/API.

**Comment by phelipebf** [comment]
Não é necessário atualizar o plugin. Fix aplicado no backend.
